### ISSUE TITLE
Improve Tickets List View Layout

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#197]
The (admin) tickets list view is not optimal. The idea of the quick activity stream was good but the way it is currently done doesn't make the plugin easier to use.

First of all, I think we need to brainstorm about what's needed in the list view to make it really useful. Currently, the available columns are:

* Status
* ID
* Title
* Tags
* Support Staff
* Activity
* Custom Fields

The custom fields will obviously remain because it is set by the user. Custom fields aren't a concern here.

## Proposition

I think `Status`, `Title`, `Tags` and `Support Staff` are musts. I personnaly don't use `ID` but it's been requested by users so let's say we keep it. Maybe it could be merged with the `Title` column though, as we don't really need any filtering on it.

It's been requested many times to have a `Client` column. I'm not against adding this. In this case, the `Activity` column as it currently is would loose some of its usefulness.

Here is one possibility for re-organizing the list view:

| CB | Title | Tags | Custom Fields | Support Staff | Client | Latest Activity |
| --- | --- | --- | --- | --- | --- | --- |
| [ ]   | #3267 - My Ticket Title | tag 1, tag 2 | custom fields | Agent Doe | Client Doe | Client Doe replied 2 days ago |

`Latest Activity` would simply contain the latest thing done: agent replied, client replied, ticket transferred...

The one thing I absolutely don't want to loose is a link to the latest reply. I hate scrolling down from the top when there are 10+ replies in a ticket.

**Comment by elindydotcom** [comment]
I think it is impossible to please everyone on this screen.  Your best bet is to make the screen as configurable as possible.  As such, here is what I would do if I were to be redoing this screen.

1.  Create an option for the user to add and remove columns.  You can create a few sets of typical columns that ship with the product (yes, it means being able to create and save "column profiles").  Note that there are plugins that probably allow you to do this already since tickets seems to be a CPT.  So if you do this you might want to make sure you play nicely with those other more general purpose plugins.

2.  Have an option for each row to be TWO lines.  The second line can also be any number of columns but generally would be used for either last reply preview or latest activity.  Some users will be happy with one line, some with prefer working two lines. Someone like myself would be switching back and forth between them and between column profiles.  (This means quick toggles at the top of the screen to switch between single and double lines and to quick select a column profile).

3.  Have an option for split screen - columns on the left, details on the right.   User can quickly scroll down tickets on the left using the down arrow key with the details (with more fields) showing up on the right hand side.

4.  The usual options for sorting and filtering.  Bulk updates (with "select all" and "select none" option on the currently filtered view).  Common bulk updates would be to quickly clear our old tickets, reassign tickets to new support staff  (common when someone leaves the company) etc.  Plus bulk deleting, archiving, changing status etc.

5.  Quick edit options similar to the quick edit view for POSTS.  Though, in this case the user/admin  would be able to configure which fields go into the quick edit view).

I hope this helps.  It's an ambitious request but you asked <grin>.

**Comment by WHMpress** [comment]
1. Activity column must be sort-able by last replied. Tickets that support have just replied are hard to find.
2. There should be client/ client email search. 
3. Client column should be seperate, Currently if last reply is by staff, one need to open each ticket one by one to to find a ticket by a specific client.
4. An option to list all tickets by a specific customer.

**Comment by 1BJK903** [comment]
I agree that it needs a redesign, but it isn't it better to give users the capability to show all the fields on the front-end, so that the Wordpress backend stays relatively simple, but the front-end full with all the information the user agents need?

**Comment by KasperTA** [comment]
I use www.admincolumns.com to edit columns in all my plugins views, so for me it's a waste of the developers time for him Julien to work on user configurability of columns within Awesome Support. I would think everybody who really needs configurable columns need it for more than a single plugin anyway.

**Comment by z1j1888** [comment]
should display the ticket creator's name.

**Comment by visualmodo** [comment]
Hello plugin devs
I'm using your great plugin since 2014 (2.0 version) and all is good however I really would like to see the clients profile on the 'all tickets' page and I'd also want to this client's names (on the all tickets page) can be clickable for I see the old client's tickets, this will help me a lot and I'm sure it will help everyone. 

Heave a great day!

**Comment by ivo82** [comment]
Hello, 

1. Order number is key for us. In fact it's the main reason for which we upgrader from 2.x to 3.x. So I hope you arent going to cut it! (I dont see it on your list so I'm worried)

2. I can head to "Screen Options" and hide the fields that I don't need. So, actually, I don't think it's a problem to have 10-12 fields and let each user customize it. 

Hope this helps!

**Comment by tripflex** [comment]
Yes I agree with @ivo82 as what I've always done in the past with my plugins is add the code for handling a large amount of different columns, but setting only basic ones as default and this would still allow users to decide how they want columns to show up.

I've owned a hosting company for a long time, that along with my WP dev company, I've spent a lot of time dealing with, testing, extending, and cursing out different support systems .... and the one feature that is a *must* for me, is sortable table based on last reply ... this way I can sort my tickets based on when the last reply was made.  I'm just now setting up my first test for AS so we will see how it goes ... if anything i'll just add that functionality myself (if it doesn't already exist)

**Comment by WHMpress** [comment]
yes, sorting by last reply is one of the most needed

**Comment by vladab** [comment]
Here is a link to my customization of the plugin, they includes the feature to filter by assignee and other customizations.

Some of them needed to overwrite the template file maybe we can talk to add some filter so this can be done without the changing plugin files or include some of them into the plugin.

Great work guys! Keep it up! ")

**Comment by f4bsch** [comment]
Hi,
I developed smart priority ranking that sorts tickets by a calculated priority.
It's a linear weighting algorithm that evaluates tickets on
* last reply time by client or agent
* if reply is required (upon keyword detection)
* client respond behaviour
* ...

Is there any interest in this?

**Comment by tripflex** [comment]
@f4bsch I love this idea, even if we had to add a checkbox or something

- [ ] Response Expected

to help determine if the reply from the client was something being waited on, or if it was just the client replying saying "Thanks"

**Comment by julien731** [comment]
Oh yeah very interested @f4bsch ! That sounds excellent :)

**Comment by nschvabenitz** [comment]
I just added a feature request that included a dashboard widget that could be used to view support tickets for agents who have been assigned to that ticket. I think this would be really helpful for the agent assigned to the ticket. So that he or she can see if the customer has responded and if further action is needed by the support agent. If no action is needed after a period of time lapses. The ticket could be closed from the widget. Or maybe some kind of auto-close function could be built in where the ticket is closed after a specified period of time lapses.
