### ISSUE TITLE
Logic Issue with Empty Replies

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#216]
Replies can't currently be submitted empty, which would make sense, but it then prevents users from closing a ticket without a reply.

We should allow them to do so and it requires changes at 2 levels: server side validation and front-end validation.

Regarding the server side, the filter `wpas_can_reply_be_empty` is just useless. Instead, we should:

1. Check if the ticket is set to be closed
2. Possibly close it
3. Redirect with a notification being either "reply was empty" if no close is required, "successfully closed" if close was required

**Comment by adaptifyDesigns** [comment]
@julien731 @SiamKreative 
I have the latest version installed (3.2.5) but I still am seeing this issue. If "close this ticket" checkbox is ticked, and reply textarea is empty, user cannot submit.

Could you take another look at this?

**Comment by SiamKreative** [comment]
**Looks like the "Reply & Close" back-end function does not work with an empty reply**. There must be checks that should to be removed. I think it would be best to give the ability to support agents to close a ticket from here, so that they don't have to scroll all the way up to find the "Close ticket" button if there is +30 replies...

@julien731
