### ISSUE TITLE
Unclear Pagination in Ticket Details

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#255]
Second time already that a client can't find agent replies. The replies are shown, but not on the first page.   The pagination needs to be made clearer so that people don't miss it.

**Comment by SiamKreative** [comment]
### Current issues
* If the user clicks on the "Newer replies", the original ticket is still showing up. That's like super confusing. I think that the original reply ticket should actually be considered as a regular reply, and sorted chronologically like the other replies. 
* The user has no idea how many more replies are hidden
* If we change the replies order to **New to Old**, the button still reads `Newer Replies >`, while it should say "Older replies". When going to the second pages, it reads `< Older Replies`. 

### Possible solutions
* Option to use Lazy loading. Requires AJAX but might feel more intuitive (as you can see everything in one page), and feels faster.
* Improved styling of prev/next buttons, with indicator "Showing only 10 replies. Click here to show 5 newest replies"

**Comment by SiamKreative** [comment]
http://uxmovement.com/navigation/avoid-the-pains-of-pagination/

**Comment by SiamKreative** [comment]
![image](https://cloud.githubusercontent.com/assets/1778633/14598815/3a7cd9cc-057e-11e6-9cb4-9eba175a87a0.png)

**Comment by SiamKreative** [comment]
@julien731 

You should add `ticket_id` to the JavaScript object, so that we can access it on every plugin's page.

The AJAX functions should be `wpas_load_replies` and it should return:
* current: amount of replies shown
* total: total amount of replies
* html: the HTML for the replies that will be added

See more: https://github.com/Awesome-Support/Awesome-Support/blob/4ab1beec49078955c59cd12036bef3588037ea15/assets/public/js/component_replies.js

**Comment by SiamKreative** [comment]
### Possible issues
* The user gets confused when after submitting a reply because it's back to normal state (not all replies  are shown). Might be able to work something out with the history API.

**Comment by julien731** [comment]
Closed by 0372e713f58c6a01c92ca381209410423127e0ce
