### ISSUE TITLE
Attachment issue with iThemes Security

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#289]
[iThemes Security](https://wordpress.org/plugins/better-wp-security/) is adding the following line to the `.htaccess` that breaks links to display attachments (creates a 404):

```
# End Abuse HTTP Referrer Blocking
RewriteRule ^.* – [F,L]
```

**Comment by SiamKreative** [comment]
> Hi, I found it
The ithemes security are re-writing the .htaccess file every time that the settings are saved, then I found the issue,when activate
Default Blacklist
Enable HackRepair.com’s blacklist feature
the files with lines added to .htaccess are on plugins/better-wp-security/core/modules/ban-users/lists/hackrepairs-*.inc
I strip just the line that make the conflict in hackrepair-apache.inc without deactivate the blacklist, (but I’ll must do it every update of the plugin)
I understand that a file is used depending on the server
Hope you can find a solution or can contact iThemes security authors to make these plugins compatibles ;)
regards

**Comment by SiamKreative** [comment]
**Friday, March 25, 2016:**
https://wordpress.org/support/topic/compatibility-with-awesome-support-plugin?replies=1

**Comment by aaroncampbell** [comment]
Hey Julien,
I'm Aaron, lead developer on iThemes security. I'm not sure exactly what is conflicting for you, but I'd be happy to try to help fix this conflict.

The rewrite rule you're talking about is listed a little out of context here, because you're missing all the rewrite conditions that come before it. The single line you pasted will throw a 403 (forbidden, the 'F' flag there), **_if_** any of the previous conditions have been met (since they are all chained together with the OR flag).

[View the rewrite rule in context](https://plugins.trac.wordpress.org/browser/better-wp-security/trunk/core/modules/ban-users/lists/hackrepair-apache.inc)

I'm not sure how you are triggering any of those conditions, but maybe we can start by looking at the whole of the .htaccess file, then looking at the actual request that's getting denied, and then trying to track down which condition is actually being triggered?

**Comment by SiamKreative** [comment]
Hey @aaroncampbell,

Thanks for getting back to me. I will run tests this afternoon to identify precisely what is going on.

cc @julien731
