### ISSUE TITLE
:-( NOOOOOOOOOOOOO!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by BurlesonBrad** [Awesome-Support/Awesome-Support#326]
https://flippa.com/6410433-getawesomesupport-com

Jeeze....  If money was the issue, then I'd much rather make a larger gradual buyout of the plugin with a 6 month marketing plan from someone ( :hand: <--raises hand!)  than do one payout dipping into our bank account all at once and a smaller _one-time_ sale.

Regardless @julien731 it's sad to see it go.  
Many inquiring minds want to know though.... **_why?_**

**Comment by julien731** [comment]
Hi Brad,

Sorry you had to find out this way. We're not publicly communicating about it to not scare our customers.

I am sad to let AS go as well, but it was inevitable. There are two main reasons for that.

The first reason is resources. We currently don't have enough resources to push the plugin forward. I have a ton of ideas for improvement, and our roadmap is quite heavy as well, but, as you can see it, the roadmap didn't change for a while now. This is because we don't have the time to provide support (let's also keep in mind we provide free support on WP.org in addition to the priority support for paid customers), fix the bugs, add new features, and develop new addons at the same time.

I believe Awesome Support is a great support plugin, but it didn't have any of the major improvements planned in a while now. I want the plugin to grow, and I feel that the best way for that is to transfer it to someone with more resources.

The other reason is that we are closing our parent company. In this process, we are closing down all our related services and products.

Now that AS is for sale, my goal is to ensure that the buyer is someone serious that will be as dedicated as we are to make AS the best support plugin for WP. We are already in touch with some people who seem quite serious about it.

Finally, even though I won't be the lead developer anymore, I want to try and continue contributing to it. I spent so much time and put so much effort in developing it that it will probably be difficult to completely stop.
